name: Benchmark this PR
on:
  pull_request_target:
    branches: [ main ]  # change to your default branch
    paths-ignore:
      - 'CITATION.bib'
      - 'LICENSE.md'
      - 'README.md'
      - '.zenodo.json'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/Documenter.yml'
      - '.github/workflows/Format-check.yml'
      - '.github/workflows/TagBot.yml'
      - '.github/workflows/SpellCheck.yml'
      - 'benchmark/**'
      - 'docs/**'
permissions:
  pull-requests: write    # action needs to post a comment

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1.10'
          bench-on: ${{ github.event.pull_request.head.sha }}
